### ISSUE TITLE
Add Serilog Sink icon to Serilog.Sinks.Discord NuGet package

### ISSUE THREAD

**Issue by augustoproiete** [serilog-contrib/Serilog-Sinks-Discord#7]
The `Serilog.Sinks.Discord` NuGet package doesn't yet have an icon.

![image](https://user-images.githubusercontent.com/177608/130721903-57175887-8c6e-424f-ae55-301c9d778138.png)

I suggest using the standard icon for sinks:

![serilog standard sink icon](https://serilog.net/images/serilog-sink-nuget.png)

---

More details: https://github.com/serilog-contrib/brand

**Comment by AblEdge** [comment]
Done ✅.
