### ISSUE TITLE
tag release versions

### ISSUE THREAD

**Issue by Felk** [serilog-contrib/Serilog-Sinks-Discord#8]
Unfortunately the repository does not have any tags, which makes it difficult to know what release version on nuget corresponds to which commit. Dependabot also isn't able to give any more information on what changed beyond "see full diff in compare view": https://github.com/TwitchPlaysPokemon/tpp-core/pull/283

**Comment by AblEdge** [comment]
Hi @Felk , sorry for delay,
could you please tell how know the mapping between releases and commits helps you?

**Comment by Felk** [comment]
Hey @AblEdge, sure,

some people might not care, but I am always reluctant to "just" update dependencies if I am unable to figure out what changed. Having git tags and being able to diff them is the next best thing if there are no hand-written changelogs available.

**Comment by AblEdge** [comment]
Ok then, thanks for your feedback🎯, I try to handle that in future releases.
